### ISSUE TITLE
你好 刚才使用了一下您的小程序，很棒，想请教两个问题

### ISSUE THREAD

**Issue by YanyingZH** [qi19901212/Garbage#6]
1.首先是训练集的问题，这些训练图片要在哪里找到
2.第二点是训练出来的模型要怎么做成小程序，这个问题确实有些大而泛了，就是希望大佬能指出一个方向。
软件大二学生，刚接触深度学习，目前水平只能做到数据增强和用VGG16等模型预训练然后全连接分类

**Comment by qi19901212** [comment]
采用百度的ai 图片识别。我没有做深度学习
