### ISSUE TITLE
请教一下域名设置的问题

### ISSUE THREAD

**Issue by XuXING0430** [qi19901212/Garbage#8]
出现了这个bug：
Error: getaddrinfo ENOTFOUND api.baidubce.com api.baidubce.com:443
域名无法解析：➜ nslookup api.baidubce.com
Server:	10.11.56.23
Address:	10.11.56.23#53
** server can't find api.baidubce.com: NXDOMAIN

请问该怎么解决？项目设置中的 域名该如何设置啊。。。。。。

**Comment by qi19901212** [comment]
小程序域名设置先百度吧，太基础了。
